### ISSUE TITLE
E10 SCRIPT438: Object doesn't support property or method 'fill'

### ISSUE THREAD

**Issue by UltraMC** [crypto-browserify/createHash#10]
`SCRIPT438: Object doesn't support property or method 'fill'`
in create-hash
`var zeroBuffer = new Buffer(intSize); zeroBuffer.fill(0);`

**Comment by fanatid** [comment]
@UltraMC are you using browserify? if so, I think it's question for [feross/buffer](https://github.com/feross/buffer/)

**Comment by UltraMC** [comment]
@fanatid yes
