### ISSUE TITLE
extract md5

### ISSUE THREAD

**Issue by fanatid** [crypto-browserify/createHash#11]
Why? Because you already extracted [sha.js](https://github.com/crypto-browserify/sha.js) and [ripemd160](https://github.com/crypto-browserify/ripemd160/), but `md5` is still here in files [md5.js](https://github.com/crypto-browserify/createHash/blob/0c6bf8403206f97f1435dabe9f60c59700d7ad7d/md5.js) and [make-hash.js](https://github.com/crypto-browserify/createHash/blob/0c6bf8403206f97f1435dabe9f60c59700d7ad7d/make-hash.js). Also it's help with https://github.com/crypto-browserify/EVP_BytesToKey/issues/3.

If you're agree I can create this package and then transfer to organization `crypto-browserify`.

**Comment by calvinmetcalf** [comment]
go for it

**Comment by fanatid** [comment]
Depends from https://github.com/crypto-browserify/sha.js/issues/25

**Comment by fanatid** [comment]
@calvinmetcalf I extracted md5 -- http://github.com/fanatid/md5.js (based on hash-base -- http://github.com/fanatid/hash-base).
I also added you on npm! (You can add other crypto-browserify members and remove me, I don't object)

Can we discuss this packages? and after I continue with integration hash-base to sha.js and ripemd160..
I wanted transfer repositories, but found that I should have admin rights... :( but we can ask github support about this!
![screenshot at 2016-04-04 19 27 57](https://cloud.githubusercontent.com/assets/2633065/14255188/f55b71a8-faa3-11e5-801c-79ec27e9f1a9.png)

cc @dcousens @dominictarr @jprichardson

**Comment by calvinmetcalf** [comment]
md5 looks good

**Comment by fanatid** [comment]
@calvinmetcalf what you think about `DEFAULT_ENCODING` in `hash-base`?

**Comment by calvinmetcalf** [comment]
- why is it a static method on the creatHash class?
- it should be an if/else if not an if/if

**Comment by fanatid** [comment]
> why is it a static method on the creatHash class?

it's static because in node crypto this is static
in createHash we can use getter/setter (and reassign in md5.js, sha.js, ripemd160)

> it should be an if/else if not an if/if

if/if because we should change `buffer` -> `binary` (`new Buffer('data', 'buffer')` is invalid)

**Comment by calvinmetcalf** [comment]
so default encoding is on the crypto module not the individual modules, if we were to implement that I don't think this would be the way to do it

**Comment by fanatid** [comment]
yes, `DEFAULT_ENCODING` is top property and I don't know how implement this in small modules
should we support this feature?

**Comment by calvinmetcalf** [comment]
I will live if we don't, nobody has complained yet

**Comment by calvinmetcalf** [comment]
nodejs/node#6042

**Comment by dcousens** [comment]
Close in favour of https://github.com/crypto-browserify/createHash/pull/19
