### ISSUE TITLE
update version of ripemd160

### ISSUE THREAD

**Issue by fanatid** [crypto-browserify/createHash#12]
I working on adding [hash-base](https://github.com/fanatid/hash-base) to [sha.js](https://github.com/crypto-browserify/sha.js), after this I'll update this package for using new [ripemd160](https://github.com/crypto-browserify/ripemd160/) and [sha.js](https://github.com/crypto-browserify/sha.js)

**Comment by dcousens** [comment]
Close in favour of https://github.com/crypto-browserify/createHash/pull/19
