### ISSUE TITLE
current npm version 1.1.2 of package create-hash does not support md5 stream calcualtion

### ISSUE THREAD

**Issue by XiaoningLiu** [crypto-browserify/createHash#15]
Hi,

**For package create-hash, current npm version 1.1.2 doesn't support md5 calculation based on stream.**

We need buffer all the data in memory and then calculate the md5.
It's not possible for calculating md5 of huge files.

@fanatid had created the md5.js module based on stream.
There is also a branch named **feature/update-hashes**.

**_It's possible to update the npm version based on this branch?_** 

I'm also willing to help during the update.

Best,
Xiaoning

**Comment by calvinmetcalf** [comment]
I'm on vacation but can take a look next week

**Comment by XiaoningLiu** [comment]
Great thanks!

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/createHash/pull/19, related to https://github.com/crypto-browserify/createHash/issues/11
