### ISSUE TITLE
does this need to be a major bump?

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/createHash#21]
in the most recent version we got rid of md5.js, which some things were depending on, and while I believe none of the ones we have do anymore things might still

**Comment by calvinmetcalf** [comment]
the other easeir thing might just be to put a md5.js file in there that uses the md5 module

**Comment by calvinmetcalf** [comment]
see #22

**Comment by dcousens** [comment]
No major bump required if the API was restored.
