### ISSUE TITLE
incorrect hash in android 4.3.1 and lower

### ISSUE THREAD

**Issue by rubensayshi** [crypto-browserify/createHash#8]
when using `createHash('sha256')` I'm getting to hash `'synchronous write'` I'm getting  
`1e0a06bb7cb5399c5389c14ff182b700834f9a00bcfd5b0067e12bdde24a5300` instead of   `1e0a06bb7cb5399c5389c14ff182b748834f9aedbcfd5bb467e12bdde24a5370`.

using `crypto-js` I'm getting the correct hash.

I'm using this repo to test it with inside an Android 4.3.1 emulator (Nexus 4 Intel Atom x64):  
https://github.com/rubensayshi/browserify-cryptojs-android

using node v0.10 or v0.12 to browserify and run cordova doesn't make a difference

**Comment by rubensayshi** [comment]
idk if it's me or not ... 
if anyone has any ideas of things to test without wanting to spend time actually coding/running it then just tell me and I'll do it ;-)

**Comment by calvinmetcalf** [comment]
what the actual code your using to hash the value, when I do

```js
crypto.createHash('sha256').update('synchronous write').digest('hex');
```

I get

```js
1e0a06bb7cb5399c5389c14ff182b748834f9aedbcfd5bb467e12bdde24a5370
```

**Comment by rubensayshi** [comment]
ooops sorry, yea, was trying difference message, updated original post now.

the odd (or maybe not) thing is that the result is always very similar (when I manually compare I can barely see the difference).

**Comment by calvinmetcalf** [comment]
yeah looks to be an issue with the sufix of the hash

**Comment by calvinmetcalf** [comment]
(in the browser createHash and crypto.createHash are actually the same)

**Comment by calvinmetcalf** [comment]
I hopefully will be able to get to this this weekend

**Comment by dcousens** [comment]
``` javascript
1e0a06bb7cb5399c5389c14ff182b7 00 834f9a 00 bcfd5b 00 67e12bdde24a53 00 1e0a06bb7cb5399c5389c14ff182b7 48 834f9a ed bcfd5b b4 67e12bdde24a53 70
```

It isn't just the suffix

**Comment by calvinmetcalf** [comment]
ok able to confirm that the issue is not present on android 4.4 (which as it turns out is the oldest devise I own) installing the emulator now

**Comment by calvinmetcalf** [comment]
ok so testing on an emulator running 4.3.3 (modifing the test page to print to the dom) I am unable to reproduce the problem
<img width="519" alt="screen shot 2015-10-03 at 11 25 30 am" src="https://cloud.githubusercontent.com/assets/1128607/10263595/a2434fa4-69c1-11e5-94dc-3592c17f43da.png">

**Comment by calvinmetcalf** [comment]
so that being said I am giving another go at setting up browser tests for the whole module family (crypto-browserify/crypto-browserify#139) which should catch this.

**Comment by dcousens** [comment]
@rubensayshi do you have a more in depth reproduction environment?

**Comment by calvinmetcalf** [comment]
aha! reproduced it! https://api.travis-ci.org/jobs/83552020/log.txt?deansi=true

**Comment by rubensayshi** [comment]
I was testing on 4.3.1, maybe 4.3.3 is already a working version ...

**Comment by calvinmetcalf** [comment]
it seems to be a issue with the browserify buffer implementation as I've been able to write a failing test there.

**Comment by dcousens** [comment]
See https://github.com/feross/buffer/pull/81
